name: Deploy Pages + Worker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      PAGES_URL: ${{ secrets.PAGES_URL }}
      WORKER_URL: ${{ secrets.WORKER_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Deploy Worker & M3U8
        run: python deploy_worker.py

      - name: Test Worker
        run: python test_worker_pages.py
